name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - numpy
  - matplotlib
  - ipywidgets
  - xeus-cpp
  - pip:
      - ipycanvas
      - jupyterlab-open-url-parameter
      - rise
      - ipydrawio[all]
      - jupyterlab-git
      - jupyterlite-pyodide-kernel
      - jupyterlite-javascript-kernel
      - ipympl
      - plotly
      - bqplot