name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - ipycanvas
  - rise
  - jupyterlab-rise
# https://pypi.org/project/jupyterlite-xeus-python/ der xeus-python Kernel benutzt das hier
